version: "2.0"
services:
    redis:
        image: redis
        ports:
            - "6379:6379"

    postgres:
        restart: always
        image: sameersbn/postgresql:9.6-2
        ports:
            - "5432:5432"
        environment:
            - DEBUG=true
            - DB_USER=thanqueue
            - DB_PASS=thanqueue
            - DB_NAME=thanqueue
        volumes:
            - ./data/postgres:/var/lib/postgresql

    elasticsearch:
        hostname: elastic
        domainname: elk-local
        image: elasticsearch:5.6.4
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - ES_JAVA_OPTS=-Xms1G -Xmx1G
        volumes:
            - $PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticearch.yml
            - ./data/elasticsearch:/data

    kibana:
        hostname: kibana
        domainname: elk-local
        image: kibana:latest
        ports:
            - "5601:5601"

    logstash:
        hostname: logstash
        domainname: elk-local
        command: logstash -e 'input { stdin {  } http { port => 8080 } } output { elasticsearch { hosts => [ 'elasticsearch' ] index => "elk-data-%{+YYYY.MM.dd}" } stdout { } }'
        image: logstash:latest
        ports:
            - "8080:8080"